on:
  push:
    branches:
    - main

jobs:
  prebuild:
    name: Prepare for building
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.email != 'github-actions[bot]@users.noreply.github.com'
    permissions:
      contents: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
 
      - name: Detect changed notes
        run: |
          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^3rd Year/Analisi e Calcolo Numerico/notes'; then
            echo "::set-output name=acn_changed::true"
          else
            echo "::set-output name=acn_changed::false"
          fi

          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q '^3rd Year/Programmazione di Sistemi Embedded e Multicore/notes'; then
            echo "::set-output name=psem_changed::true"
          else
            echo "::set-output name=psem_changed::false"
          fi

  build_acn:
    name: Build Analisi e Calcolo Numerico
    runs-on: ubuntu-latest
    needs: prebuild
    if: needs.check-files.outputs.acn_changed == 'true'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Tectonic
        run: |
          sudo apt install curl
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh

      - name: Compile the template
        run: |
          ./tectonic "main.tex" -Z continue-on-errors --color=always

      - name: Commit PDF
        run: |
          mv main.pdf "Analisi e Calcolo Numerico.pdf"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "Analisi e Calcolo Numerico.pdf"
          git commit -m 'Add compiled ACN notes'

      - name: Push PDF
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"

  build_psem:
    name: Build Programmazione di Sistemi Embedded e Multicore
    runs-on: ubuntu-latest
    needs: prebuild
    if: needs.check-files.outputs.psem_changed == 'true'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Tectonic
        run: |
          sudo apt install curl
          curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh

      - name: Compile the template
        run: |
          ./tectonic "main.tex" -Z continue-on-errors --color=always

      - name: Commit PDF
        run: |
          mv main.pdf "Programmazione di Sistemi Embedded e Multicore.pdf"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add "Programmazione di Sistemi Embedded e Multicore.pdf"
          git commit -m 'Add compiled PSEM notes'

      - name: Push PDF
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
